name: lens_mark
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  exif: ^3.3.0
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_exif_rotation: ^0.5.2
  flutter_riverpod: ^2.5.1
  google_fonts: ^8.0.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/presets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
